# Generated by Django 6.0.1 on 2026-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gymfollower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/'),
        ),
    ]
